### ISSUE TITLE
Make the plugin compatible with GVim

### ISSUE THREAD

**Issue by t-pohl** [jannis-baum/vivify.vim#19]
I really like the plugin but it seems that I can only open it from the "normal" vim. `:Vivify` does not seem to do anything when invoked out of Gvim.

**Comment by t-pohl** [comment]
Problem was missing VIV_PORT variable

**Comment by t-pohl** [comment]
Yes, you are completely right. If I do not set this variable the command hangs indefinitely.
Apart from this minor bug, great work!

**Comment by jannis-baum** [comment]
Thanks! Does this also happen when you call Vivify from the terminal, i.e. `viv <file>`? If so, it's probably related to https://github.com/jannis-baum/Vivify/issues/157 which was just opened earlier.

**Comment by t-pohl** [comment]
It also happens on the terminal so I'm pretty sure that this is a duplicate.

**Comment by jannis-baum** [comment]
Thanks! I think I fixed it in https://github.com/jannis-baum/Vivify/pull/158, if you or the OP of the other issue can confirm that that works I'll merge it and make a new release :)

**Comment by t-pohl** [comment]
Very cool, that you fixed it that fast :) Going to wait for the confirmation from the other poster and then install the new release.
