### ISSUE TITLE
Image files with spaces in their file name arent possible to embed

### ISSUE THREAD

**Issue by binEpilo** [jannis-baum/vivify.vim#22]
I dont really know whether this is just some markdown rule, but if I type

![](file name.jpg) to import the image "file name.jpg" it doesnt work.

Is this a bug or a markdown feature?

**Comment by jannis-baum** [comment]
Hello! I can't try this out right now but if you want to look into you could try [using `%20` to escape the spaces](https://stackoverflow.com/a/62833782). In case that doesn't work I can look into it later/in the next days :)

**Comment by tuurep** [comment]
Oh yes, hadn't thought about that. Looks like it's kind of a limitation of Markdown in general, found this video giving 2 different ways to get around it:

https://www.youtube.com/watch?v=i7_3CsNVtjQ

I tested these out, you can either write the space as `%20`, or wrap the path in `<>` brackets:

```md
![](file%20name.jpg)
![](<file name.jpg>)
```

The angle-bracket solution seems especially reasonable to me

**Comment by tuurep** [comment]
Haha we replied at the same time.. but hey I think I had something to add
