### ISSUE TITLE
Configurable ports

### ISSUE THREAD

**Issue by jannis-baum** [jannis-baum/vivify.vim#8]
Vivify has a config option to change the port. vivify.vim currently only checks the ENV variable and otherwise falls back to the default port:

https://github.com/jannis-baum/vivify.vim/blob/7f763bc447bc6dd3ec646c9489edaae52f453290/autoload/vivify.vim#L1

If Vivify's config sets the port to something else, this plugin will never work because Vivify will never start on the port Vim is looking for it

**Comment by jannis-baum** [comment]
Currently I see two options:

1. Parse the config from the editor plugin. This seems very tedious and would make integrating Vivify into new editors significantly more work because right now it is very simple
2. Simply remove the option to configure the port in Vivify

I would argue *2.* is fine because I don't feel like this is something people would care about. The only issue would be if some other tool runs at that exact port, but I also feel like this seems very unlikely. @tuurep I would highly appreciate a second opinion on this!

**Comment by tuurep** [comment]
Mmmm I'm not sure what to say but do I understand correctly that with the environment variable you can simply achieve the same as with the config option?

So it could be set in e.g. .bashrc like:

```
export VIV_PORT=88888
```

So maybe that mitigates the possible drawback?

The way you word the option 1 makes it sound like we really want to avoid it :smile:

**Comment by jannis-baum** [comment]
> Mmmm I'm not sure what to say but do I understand correctly that with the environment variable you can simply achieve the same as with the config option?
> 
> So it could be set in e.g. .bashrc like:
> 
> ```
> export VIV_PORT=88888
> ```
> 
> So maybe that mitigates the possible drawback?

Yes that's true!

> The way you word the option 1 makes it sound like we really want to avoid it 😄

😁

---

I will remove the config-file-based port selection from main Vivify then ^^
