### ISSUE TITLE
`:h vivify` doc

### ISSUE THREAD

**Issue by tuurep** [jannis-baum/vivify.vim#9]
I really appreciate when plugins have this, mainly to check which commands/g:options/mappings are provided

Here's an example:

https://github.com/tommcdo/vim-lion/blob/master/doc/lion.txt

After adding an option for refresh event in #5, I think it'd be especially nice to have a `:h` page. But it can be quite tiny.

Do you approve? I can write it, but you can as well if that's something you want to do.

**Comment by jannis-baum** [comment]
Yes 100% approve and would appreciate if you want to do it! :)
